# Generated by Django 3.2.5 on 2021-10-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyleblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.CharField(default='Description', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.TextField(default='Image URL'),
            preserve_default=False,
        ),
    ]
